{{- $cluster_name := .Values.cluster_name -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kubernetes-config-collector.fullname" . }}
  labels:
    {{- include "kubernetes-config-collector.labels" . | nindent 4 }}
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 1200
      template:
        spec:
          serviceAccountName: {{ include "kubernetes-config-collector.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            env:
              - name: CLUSTER_ID
                value: "{{ $cluster_name }}"
              - name: SECRET_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: shinobi-integration-secret
                    key: shinobiClientApiKey
              - name: SHINOBI_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: shinobi-integration-secret
                    key: shinobiClientEndPoint
          restartPolicy: OnFailure
