{{- $api_key := .Values.shinobi.api_key -}}
{{- $endpoint := .Values.shinobi.endpoint -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: shinobi-integration
  name: shinobi-integration-secret
type: Opaque
data:
  shinobiClientApiKey: {{ $api_key | b64enc }}
  shinobiClientEndPoint: {{ $endpoint | b64enc }}
